// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Uw8q4ZfAD8DvD8x0ols6nrEgisGSy7E',
    appId: '1:330080615338:web:826f02c1e0c806088649d3',
    messagingSenderId: '330080615338',
    projectId: 'flutter-chat-app-33045',
    authDomain: 'flutter-chat-app-33045.firebaseapp.com',
    storageBucket: 'flutter-chat-app-33045.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRCxkR3gAlTOuU02Cmz1dOoNz3qD42R7k',
    appId: '1:330080615338:android:2a72324f29621ad88649d3',
    messagingSenderId: '330080615338',
    projectId: 'flutter-chat-app-33045',
    storageBucket: 'flutter-chat-app-33045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC44GrsvpGkcn5eIqjDOri3iWylHhre09c',
    appId: '1:330080615338:ios:2eccd8bb1a3d8d7e8649d3',
    messagingSenderId: '330080615338',
    projectId: 'flutter-chat-app-33045',
    storageBucket: 'flutter-chat-app-33045.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC44GrsvpGkcn5eIqjDOri3iWylHhre09c',
    appId: '1:330080615338:ios:5a80058fb97f55878649d3',
    messagingSenderId: '330080615338',
    projectId: 'flutter-chat-app-33045',
    storageBucket: 'flutter-chat-app-33045.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
