// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2jD58BpdIV2t-eCbLdPsVwLTlSy2y0X8',
    appId: '1:751779945896:web:9c3b9a359c6be18aed919d',
    messagingSenderId: '751779945896',
    projectId: 'dnsintro',
    authDomain: 'dnsintro.firebaseapp.com',
    storageBucket: 'dnsintro.appspot.com',
    measurementId: 'G-EFQMPGYTBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLTYClXlQi_jieS3CAgr5jezVnDTywCho',
    appId: '1:751779945896:android:7b9bc6c0fc4335aaed919d',
    messagingSenderId: '751779945896',
    projectId: 'dnsintro',
    storageBucket: 'dnsintro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANpttfp4t6KqERgM7i-CBB3POslcYOgiw',
    appId: '1:751779945896:ios:aa899c073040271fed919d',
    messagingSenderId: '751779945896',
    projectId: 'dnsintro',
    storageBucket: 'dnsintro.appspot.com',
    iosBundleId: 'com.example.dnsIntro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANpttfp4t6KqERgM7i-CBB3POslcYOgiw',
    appId: '1:751779945896:ios:eafb2b70cc09d3abed919d',
    messagingSenderId: '751779945896',
    projectId: 'dnsintro',
    storageBucket: 'dnsintro.appspot.com',
    iosBundleId: 'com.example.dnsIntro.RunnerTests',
  );
}
